"""
Local parcel owner index — in-memory name lookup backed by a JSONL cache.

Loads data/cache/parcel_owner_index.jsonl (written by pull_parcel_owner_index.py)
and exposes a fetch_fn compatible with APNResolver. Injecting this as the
fetch_fn replaces live assessor API queries with local lookups, enabling
deterministic exact and ordered-token name matching without network calls.

Usage with existing APNResolver + probate_parcel_matcher:

    idx = LocalParcelIndex().load(CACHE_PATH)
    resolver = APNResolver(fetch_fn=idx.fetch_fn)
    result = match_record(detail, resolver)   # unchanged call — local index used
"""
from __future__ import annotations

import json
import re
from pathlib import Path

# Patterns for WHERE clauses generated by APNResolver._build_strategies()
# and APNResolver.resolve_by_apn(). Use fullmatch to prevent partial matches.
_LIKE_MULTI = re.compile(
    r"OWNER_NAME LIKE '%([A-Z0-9]+)%([A-Z0-9]+)%'", re.IGNORECASE
)
_LIKE_SINGLE = re.compile(
    r"OWNER_NAME LIKE '%([A-Z0-9]+)%'", re.IGNORECASE
)
_APN_DASH_EQ = re.compile(r"APN_DASH = '([^']+)'", re.IGNORECASE)
_APN_EQ = re.compile(r"APN = '([^']+)'", re.IGNORECASE)


def _ordered_match(text: str, t1: str, t2: str) -> bool:
    """Return True if t1 appears in text before (and non-overlapping with) t2."""
    i = text.find(t1)
    if i == -1:
        return False
    return text.find(t2, i + len(t1)) != -1


class LocalParcelIndex:
    """In-memory parcel owner index loaded from a JSONL cache file.

    Each JSONL line is a flat attribute dict (no 'attributes' wrapper, no
    geometry). fetch_fn wraps each match back into the ArcGIS feature format
    APNResolver expects: {"attributes": {...}}.

    Pre-uppercases OWNER_NAME at load time to eliminate per-query .upper()
    calls in the inner scan loop.
    """

    def __init__(self) -> None:
        self._records: list[dict] = []
        self._names_upper: list[str] = []    # parallel list, pre-uppercased
        self._apn_idx: dict[str, int] = {}       # APN (raw) → record index
        self._apn_dash_idx: dict[str, int] = {}  # APN_DASH → record index

    def load(self, jsonl_path: Path) -> "LocalParcelIndex":
        """Load JSONL into memory, build APN lookup indexes, return self."""
        self._records = []
        self._names_upper = []
        self._apn_idx = {}
        self._apn_dash_idx = {}

        with open(jsonl_path, encoding="utf-8") as fh:
            for line in fh:
                line = line.strip()
                if not line:
                    continue
                try:
                    attrs = json.loads(line)
                except json.JSONDecodeError:
                    continue
                i = len(self._records)
                self._records.append(attrs)
                self._names_upper.append((attrs.get("OWNER_NAME") or "").upper())
                apn = (attrs.get("APN") or "").strip()
                apn_dash = (attrs.get("APN_DASH") or "").strip()
                if apn:
                    self._apn_idx[apn] = i
                if apn_dash:
                    self._apn_dash_idx[apn_dash] = i

        return self

    @property
    def record_count(self) -> int:
        return len(self._records)

    def fetch_fn(self, where: str, n: int) -> list[dict]:
        """APNResolver-compatible fetch_fn backed by the local index.

        Parses OWNER_NAME LIKE patterns and APN/APN_DASH equality clauses.
        Returns features in ArcGIS format: [{"attributes": {...}}, ...].

        Check order: APN_DASH → APN → two-token LIKE → single-token LIKE.
        Two-token LIKE must be checked before single-token to prevent the
        single-token pattern from partially matching two-token WHERE clauses.
        """
        where = where.strip()

        m = _APN_DASH_EQ.fullmatch(where)
        if m:
            i = self._apn_dash_idx.get(m.group(1).strip())
            return [{"attributes": self._records[i]}] if i is not None else []

        m = _APN_EQ.fullmatch(where)
        if m:
            i = self._apn_idx.get(m.group(1).strip())
            return [{"attributes": self._records[i]}] if i is not None else []

        m = _LIKE_MULTI.fullmatch(where)
        if m:
            t1, t2 = m.group(1).upper(), m.group(2).upper()
            results: list[dict] = []
            for i, name_upper in enumerate(self._names_upper):
                if _ordered_match(name_upper, t1, t2):
                    results.append({"attributes": self._records[i]})
                    if len(results) >= n:
                        break
            return results

        m = _LIKE_SINGLE.fullmatch(where)
        if m:
            t = m.group(1).upper()
            results = []
            for i, name_upper in enumerate(self._names_upper):
                if t in name_upper:
                    results.append({"attributes": self._records[i]})
                    if len(results) >= n:
                        break
            return results

        return []
