# Dallas County TX — install Windows Task Scheduler daily run
#
# NOT RUN — created for operator review only. This script registers a real
# OS-level scheduled task; it is intentionally left un-executed pending
# explicit operator approval (infrastructure action, out of scope for the
# automated build step that created this file).
#
# Run once as Administrator (or with Task Scheduler write permission) when
# ready to go live:
#   powershell -ExecutionPolicy Bypass -File install_daily_task.ps1
#
# Schedules the pipeline to run every morning at 7:00 AM. clerk_recordings,
# foreclosure_notices, and the LGBS tax-sale sources are genuinely daily;
# tax_collector's underlying TRW file is only regenerated by the county
# weekly (Fridays, posted the following Monday) — re-scraping it daily just
# re-downloads/re-parses an unchanged 278MB file for no new data on most
# days. Adjust $TriggerTime below to change the run time, or change the
# default action's arguments to add --skip-tax-collector on non-Monday runs
# if a more granular weekly-vs-daily schedule is wanted later.

$TaskName    = "XCerebro-Dallas-TX-Daily"
$TriggerTime = "07:00"
$RepoRoot    = Split-Path -Parent (Split-Path -Parent $PSScriptRoot)
$CmdScript   = Join-Path $PSScriptRoot "run_dallas_daily.cmd"

# Remove existing task if it exists
if (Get-ScheduledTask -TaskName $TaskName -ErrorAction SilentlyContinue) {
    Unregister-ScheduledTask -TaskName $TaskName -Confirm:$false
    Write-Host "Removed existing task: $TaskName"
}

$action  = New-ScheduledTaskAction -Execute "cmd.exe" -Argument "/c `"$CmdScript`""
$trigger = New-ScheduledTaskTrigger -Daily -At $TriggerTime
$settings = New-ScheduledTaskSettingsSet `
    -ExecutionTimeLimit (New-TimeSpan -Minutes 45) `
    -StartWhenAvailable `
    -DontStopOnIdleEnd

Register-ScheduledTask `
    -TaskName $TaskName `
    -Action $action `
    -Trigger $trigger `
    -Settings $settings `
    -RunLevel Limited `
    -Description "Daily Dallas County TX lead intelligence pipeline (PublicSearch + TRW + LGBS scrapers)" `
    -Force | Out-Null

Write-Host "Installed task: $TaskName"
Write-Host "  Runs daily at: $TriggerTime"
Write-Host "  Script:        $CmdScript"
Write-Host "  Log:           $RepoRoot\runs\dallas_tx\dallas_pipeline.log"
Write-Host ""
Write-Host "To run immediately:  Start-ScheduledTask -TaskName '$TaskName'"
Write-Host "To remove:           Unregister-ScheduledTask -TaskName '$TaskName' -Confirm:`$false"
